In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from factor_analyzer import FactorAnalyzer # Perform statistical tests before PCA

In [3]:
df = pd.read_csv("FB.csv")
df

,status_id,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,status_link,status_photo,status_status
0,246675545449582_1649696485147474,529,512,262,432,92,3,1,1,0,0,0,0
1,246675545449582_1649426988507757,150,0,0,150,0,0,0,0,0,0,1,0
2,246675545449582_1648730588577397,227,236,57,204,21,1,1,0,0,0,0,0
3,246675545449582_1648576705259452,111,0,0,111,0,0,0,0,0,0,1,0
4,246675545449582_1645700502213739,213,0,0,204,9,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7045,1050855161656896_1061863470556065,89,0,0,89,0,0,0,0,0,0,1,0
7046,1050855161656896_1061334757275603,16,0,0,14,1,0,1,0,0,0,1,0
7047,1050855161656896_1060126464063099,2,0,0,1,1,0,0,0,0,0,1,0
7048,1050855161656896_1058663487542730,351,12,22,349,2,0,0,0,0,0,1,0
7049,1050855161656896_1050858841656528,17,0,0,17,0,0,0,0,0,0,1,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   status_id      7050 non-null   object
 1   num_reactions  7050 non-null   int64
 2   num_comments   7050 non-null   int64
 3   num_shares     7050 non-null   int64
 4   num_likes      7050 non-null   int64
 5   num_loves      7050 non-null   int64
 6   num_wows       7050 non-null   int64
 7   num_hahas      7050 non-null   int64
 8   num_sads       7050 non-null   int64
 9   num_angrys     7050 non-null   int64
 10  status_link    7050 non-null   int64
 11  status_photo   7050 non-null   int64
 12  status_status  7050 non-null   int64
dtypes: int64(12), object(1)
memory usage: 716.1+ KB

In [5]:
df_num = df.select_dtypes(include = ['float64', 'int64'])
lstnumericcolumns = list(df_num.columns.values)
len(lstnumericcolumns)

12

In [6]:
from scipy.stats import zscore
df_num_scaled=df_num.apply(zscore)
df_num_scaled.head()

,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,status_link,status_photo,status_status
0,0.646104,0.323350,1.686879,0.482727,1.983266,0.196196,0.076713,0.473570,-0.155748,-0.094957,-1.245993,-0.233666
1,-0.173192,-0.252206,-0.304144,-0.144720,-0.318454,-0.147879,-0.176010,-0.152587,-0.155748,-0.094957,0.802573,-0.233666
2,-0.006738,0.013089,0.129017,-0.024571,0.206938,-0.033187,0.076713,-0.152587,-0.155748,-0.094957,-1.245993,-0.233666
3,-0.257499,-0.252206,-0.304144,-0.231495,-0.318454,-0.147879,-0.176010,-0.152587,-0.155748,-0.094957,0.802573,-0.233666
4,-0.037003,-0.252206,-0.304144,-0.024571,-0.093286,-0.147879,-0.176010,-0.152587,-0.155748,-0.094957,0.802573,-0.233666

In [7]:
cov_matrix = np.cov(df_num_scaled.T)
print('Covariance Matrix \n%s', cov_matrix)

Covariance Matrix
%s [[ 1.00014186  0.1508643   0.25075809  0.99506451  0.30504605  0.2677898
   0.17605301  0.07514867  0.1243437   0.02874721 -0.13153369  0.10541715]
 [ 0.1508643   1.00014186  0.64072829  0.10170146  0.52129743  0.16241703
   0.32509411  0.23648623  0.22521631 -0.02334367 -0.29188709 -0.04942026]
 [ 0.25075809  0.64072829  1.00014186  0.1725164   0.82011657  0.40768568
   0.39988229  0.19999833  0.31255689 -0.02571137 -0.35483022 -0.06653382]
 [ 0.99506451  0.10170146  0.1725164   1.00014186  0.20933778  0.20782924
   0.12080097  0.05217624  0.08744305  0.03266301 -0.10055153  0.11464773]
 [ 0.30504605  0.52129743  0.82011657  0.20933778  1.00014186  0.50887022
   0.50790168  0.20762964  0.3710539  -0.02952704 -0.35179053 -0.06529185]
 [ 0.2677898   0.16241703  0.40768568  0.20782924  0.50887022  1.00014186
   0.28779702  0.08651499  0.18311248 -0.01196935 -0.0864212  -0.00312953]
 [ 0.17605301  0.32509411  0.39988229  0.12080097  0.50790168  0.28779702
   1.00014186  0.14144092  0.21194022 -0.01595372 -0.15925947 -0.03466092]
 [ 0.07514867  0.23648623  0.19999833  0.05217624  0.20762964  0.08651499
   0.14144092  1.00014186  0.14209263 -0.01449119 -0.07896406  0.02086898]
 [ 0.1243437   0.22521631  0.31255689  0.08744305  0.3710539   0.18311248
   0.21194022  0.14209263  1.00014186 -0.01479139 -0.11571171 -0.02846925]
 [ 0.02874721 -0.02334367 -0.02571137  0.03266301 -0.02952704 -0.01196935
  -0.01595372 -0.01449119 -0.01479139  1.00014186 -0.11833196 -0.02219127]
 [-0.13153369 -0.29188709 -0.35483022 -0.10055153 -0.35179053 -0.0864212
  -0.15925947 -0.07896406 -0.11571171 -0.11833196  1.00014186 -0.2911876 ]
 [ 0.10541715 -0.04942026 -0.06653382  0.11464773 -0.06529185 -0.00312953
  -0.03466092  0.02086898 -0.02846925 -0.02219127 -0.2911876   1.00014186]]

In [13]:
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)
print('\n Eigen Values \n %s', eig_vals )
print('\n')
print('Eigen Vectors \n %s', eig_vecs)

 Eigen Values
 %s [3.59628800e+00 1.78479109e+00 1.64801521e-08 1.48486541e-01
 1.25112250e+00 3.58889859e-01 5.28735394e-01 6.95632348e-01
 8.11985438e-01 8.49591639e-01 9.55282786e-01 1.02089676e+00]


Eigen Vectors
 %s [[ 2.93630543e-01  6.06641137e-01  7.15773171e-01  2.03910032e-02
  -1.12002407e-01  4.82435866e-03  3.20850086e-02  2.42016415e-02
  -6.97861393e-02  8.52072210e-02  8.18911389e-02 -1.04601450e-03]
 [ 3.47497866e-01 -2.30746002e-01 -1.26384681e-06  1.67785969e-01
   8.75480006e-02 -5.17376834e-01 -5.15597556e-01 -3.99866919e-02
  -1.69312690e-01  4.37540439e-01  1.86287704e-01  1.59573424e-02]
 [ 4.43254435e-01 -2.04910484e-01  1.73179788e-05 -6.71346886e-01
   3.92859022e-03  4.57024584e-01 -1.12734594e-01 -2.04542894e-01
  -5.09397191e-02  1.96740735e-01 -6.98659821e-02 -3.48387949e-02]
 [ 2.51769604e-01  6.40653903e-01 -6.95423734e-01 -3.90502026e-02
  -1.05702016e-01 -2.79737958e-02  2.54206909e-02  3.28768718e-02
  -8.70489869e-02  9.66955499e-02  1.02090297e-01  1.73807760e-03]
 [ 4.61255079e-01 -1.65917245e-01 -6.18696218e-02  7.03643043e-01
  -5.18155502e-02  4.72074756e-01  7.92827429e-02 -8.44140094e-02
   3.53002915e-02  4.86999544e-03 -1.39427366e-01 -3.33633828e-02]
 [ 2.96340391e-01  1.62620307e-02 -1.34885816e-02 -7.08473070e-02
  -2.11548727e-01 -4.17684976e-01 -2.93540341e-02 -4.07729726e-01
   4.88194788e-01 -3.72249407e-01 -3.77299473e-01 -3.37517224e-02]
 [ 3.08854346e-01 -1.39033435e-01 -6.11926720e-03 -1.19364205e-01
  -1.01800997e-01 -9.89072403e-02  6.43937564e-02  8.72041584e-01
   2.54094006e-01 -5.77002760e-02 -1.34291828e-01 -1.78014533e-02]
 [ 1.63130579e-01 -1.10415493e-01 -2.46986519e-03 -2.15417600e-02
   4.98793399e-02  2.79589183e-02  1.61485163e-01 -8.01933929e-02
   4.06107733e-01 -1.73120550e-01  8.16405043e-01  2.52065840e-01]
 [ 2.37246758e-01 -1.26874184e-01 -1.12235269e-03 -4.90180785e-02
  -8.92316571e-02 -1.08786107e-01 -1.31307099e-02  3.56999871e-02
  -6.61974694e-01 -6.69842952e-01  1.23557407e-01  4.24590001e-02]
 [-1.38340912e-03  6.41854579e-02  2.77128984e-08  1.08316035e-02
   2.35213036e-01  6.50090460e-02 -2.07490740e-01  2.77449796e-02
   1.24037696e-01 -1.90214360e-01  2.09968130e-01 -8.92599564e-01]
 [-2.32613706e-01  3.65506390e-02 -2.10860170e-06  3.74449557e-02
  -6.43419111e-01  2.64740805e-01 -6.39131228e-01  7.27513701e-02
   1.14406851e-01 -1.20870465e-01  1.11485989e-01  7.18869432e-02]
 [ 1.37973532e-02  2.13188742e-01  1.59933119e-07  2.08221545e-02
   6.56534644e-01  1.69162607e-01 -4.80301401e-01  8.54568120e-02
   1.43312376e-01 -2.86124118e-01 -1.58614319e-01  3.58771030e-01]]

In [16]:
idx = eig_vals.argsort()[::-1]   
eigenValues = eig_vals[idx]
eigenVectors = eig_vecs[:,idx]

In [17]:
eigenValues

array([3.59628800e+00, 1.78479109e+00, 1.25112250e+00, 1.02089676e+00,
       9.55282786e-01, 8.49591639e-01, 8.11985438e-01, 6.95632348e-01,
       5.28735394e-01, 3.58889859e-01, 1.48486541e-01, 1.64801521e-08])

In [18]:
eigenVectors

array([[ 2.93630543e-01,  6.06641137e-01, -1.12002407e-01,
        -1.04601450e-03,  8.18911389e-02,  8.52072210e-02,
        -6.97861393e-02,  2.42016415e-02,  3.20850086e-02,
         4.82435866e-03,  2.03910032e-02,  7.15773171e-01],
       [ 3.47497866e-01, -2.30746002e-01,  8.75480006e-02,
         1.59573424e-02,  1.86287704e-01,  4.37540439e-01,
        -1.69312690e-01, -3.99866919e-02, -5.15597556e-01,
        -5.17376834e-01,  1.67785969e-01, -1.26384681e-06],
       [ 4.43254435e-01, -2.04910484e-01,  3.92859022e-03,
        -3.48387949e-02, -6.98659821e-02,  1.96740735e-01,
        -5.09397191e-02, -2.04542894e-01, -1.12734594e-01,
         4.57024584e-01, -6.71346886e-01,  1.73179788e-05],
       [ 2.51769604e-01,  6.40653903e-01, -1.05702016e-01,
         1.73807760e-03,  1.02090297e-01,  9.66955499e-02,
        -8.70489869e-02,  3.28768718e-02,  2.54206909e-02,
        -2.79737958e-02, -3.90502026e-02, -6.95423734e-01],
       [ 4.61255079e-01, -1.65917245e-01, -5.18155502e-02,
        -3.33633828e-02, -1.39427366e-01,  4.86999544e-03,
         3.53002915e-02, -8.44140094e-02,  7.92827429e-02,
         4.72074756e-01,  7.03643043e-01, -6.18696218e-02],
       [ 2.96340391e-01,  1.62620307e-02, -2.11548727e-01,
        -3.37517224e-02, -3.77299473e-01, -3.72249407e-01,
         4.88194788e-01, -4.07729726e-01, -2.93540341e-02,
        -4.17684976e-01, -7.08473070e-02, -1.34885816e-02],
       [ 3.08854346e-01, -1.39033435e-01, -1.01800997e-01,
        -1.78014533e-02, -1.34291828e-01, -5.77002760e-02,
         2.54094006e-01,  8.72041584e-01,  6.43937564e-02,
        -9.89072403e-02, -1.19364205e-01, -6.11926720e-03],
       [ 1.63130579e-01, -1.10415493e-01,  4.98793399e-02,
         2.52065840e-01,  8.16405043e-01, -1.73120550e-01,
         4.06107733e-01, -8.01933929e-02,  1.61485163e-01,
         2.79589183e-02, -2.15417600e-02, -2.46986519e-03],
       [ 2.37246758e-01, -1.26874184e-01, -8.92316571e-02,
         4.24590001e-02,  1.23557407e-01, -6.69842952e-01,
        -6.61974694e-01,  3.56999871e-02, -1.31307099e-02,
        -1.08786107e-01, -4.90180785e-02, -1.12235269e-03],
       [-1.38340912e-03,  6.41854579e-02,  2.35213036e-01,
        -8.92599564e-01,  2.09968130e-01, -1.90214360e-01,
         1.24037696e-01,  2.77449796e-02, -2.07490740e-01,
         6.50090460e-02,  1.08316035e-02,  2.77128984e-08],
       [-2.32613706e-01,  3.65506390e-02, -6.43419111e-01,
         7.18869432e-02,  1.11485989e-01, -1.20870465e-01,
         1.14406851e-01,  7.27513701e-02, -6.39131228e-01,
         2.64740805e-01,  3.74449557e-02, -2.10860170e-06],
       [ 1.37973532e-02,  2.13188742e-01,  6.56534644e-01,
         3.58771030e-01, -1.58614319e-01, -2.86124118e-01,
         1.43312376e-01,  8.54568120e-02, -4.80301401e-01,
         1.69162607e-01,  2.08221545e-02,  1.59933119e-07]])

In [9]:
tot = sum(eig_vals)
var_exp = [( i /tot ) * 100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)
print("Cumulative Variance Explained", cum_var_exp)

Cumulative Variance Explained [ 29.96481572  44.83596514  55.26050708  63.76677335  71.72633406
  78.80526014  85.57084566  91.36695963  95.77246293  98.76278754
  99.99999986 100.        ]